### PR TITLE
fix: relax dev deps and remove peer deps altogether

### PR DESCRIPTION
**Pull request by kumar303**

### CODE REVIEW

**Comment by kumar303** [comment]
@rpl what do you think of this? Peer deps seem like more headache than anything else. Also, greenkeeper will nag me less if I pin the dev deps to major versions.

**Comment by rpl** [comment]
In the end, the main reason to specify a version range in the peer dependencies is to prevent issues related to updates on the peer dependencies that can breaks the package by changing their APIs (e.g. in this particular case: if grunt changes the APIs used by the grunt tasks defined by this package, or if flow changes its command line parameters).

Nevertheless, grunt is probably unlikely to make any major change to their API at this point, and the assumptions that this package does about the flow API is only related to a small subset of CLI command and options, and so maybe it would be less of a headache to just remove these peer dependencies (or, if we are still concerned about potential major changes in the APIs exposed by these peer package, to relax them by using a less strict range of versions, e.g. `"flow": ">= 0.38 < 0.50"` and `"grunt": ">= 1.0 < 2.0"`).

**Comment by kumar303** [comment]
Yeah, I think I want to live dangerously and ditch the peer deps! We can always go back later if it causes problems.

**Comment by rpl** [comment]
@kumar303 hehehe :+1: sounds good to me.

**Pull request merged**
